language: r
cache:
  packages: true
  apt: true
warnings_are_errors: false

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false

branches:
  except:
    - gh-pages
    - remove_plant_plus
    - scaffolder

r_github_packages:
  - richfitz/RcppR6
  - richfitz/grader
  - smbache/loggr
  - jimhester/covr
      
jobs:
  include:
    - os: linux
      dist: bionic
      env:
        - R_CODECOV=true
        - MAKEFLAGS="-j 2"
    - os: osx
      latex: false

script: 
  - |
    R CMD build .
    travis_wait 20 R CMD check plant*tar.gz

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::coveralls()'; fi

notifications:
  email:
    on_success: change
    on_failure: change
  slack: traitecoevo:pYviKwrn6lAvBZUOxxktBwcO
